#!/bin/bash
echo "GoAfar Web UI 已启动！"
echo ""
echo "访问方式："
echo "1. 本地访问: http://localhost:7860"
echo "2. 公网访问: 正在生成gradio.live链接..."
echo ""
echo "如果看不到公网链接，请："
echo "  - 等待30秒让Gradio完全启动"
echo "  - 查看进程输出获取链接"
echo ""
echo "当前Web UI进程："
ps aux | grep "[d]emo_ui.py"
echo ""
echo "端口监听状态："
netstat -tlnp 2>/dev/null | grep 7860 || ss -tlnp | grep 7860
echo ""
echo "提示：Gradio公网链接会在终端输出中显示为："
echo "  Running on public URL: https://xxxxx.gradio.live"
